distributed:
  logging:
    bokeh: critical
  scheduler:
    work-stealing: True
    allowed-failures: 5
  admin:
    tick:
      limit: 5s

kubernetes:
  name: dask-worker
  worker-template:
    spec:
      restartPolicy: Never
      containers:
      - args:
          - dask-worker
          - --nthreads
          - '2'
          - --no-bokeh
          - --memory-limit
          - "4GB"
          - --death-timeout
          - '60'
        image: daskdev/dask:latest
        name: dask-docker
        resources:
          limits:
            cpu: "1.5"
            memory: "4G"

labextension:
  factory:
    module: dask_kubernetes
    class: KubeCluster
    args: []
    kwargs: {}
  default:
    workers: null
    adapt:
      null
  initial:
    []

