name: tag action
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: cehappdev
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push Docker image
        run: ./build-container.sh
        shell: bash
